version: '3.5'
services:
  schema-registry:
    image: 'confluentinc/cp-schema-registry:${version_confluent}'
    hostname: schema-registry
    container_name: schema-registry
    networks:
      - tz-kafka-network
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-registry:8081'